services:
  dailyQuoteApi:
    url: localhost:3010

mysql:
  timezone: Z
  host: localhost
  database: daily_quote
  user: it_user
  password: user1234
  connectionLimit: 5
mockserver:
  host: "localhost"
  managePort: 8082
smtp:
  host: localhost
  managePort: 2080
